const KEY = 'acmPortalSettingsV1';
const DEFAULT = { template: 'assets/certificates/acm-certificate-template.png', settings: { x: .5, y: .43, fontSize: 54, fontFamily: 'Georgia', bold: true, color: '#075a3a', align: 'center', rotation: 0, letterSpacing: 0, lineHeight: 1 } };
let db = null, authenticatedUser = null;
const qs = s => document.querySelector(s);
const esc = s => String(s).replace(/[&<>"']/g, m => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[m]));
const settings = () => { try { const cached = JSON.parse(localStorage.getItem(KEY) || '{}'); return { ...DEFAULT, ...cached, settings: { ...DEFAULT.settings, ...(cached.settings || {}) } }; } catch { return { ...DEFAULT, settings: { ...DEFAULT.settings } }; } };
const saveSettings = d => localStorage.setItem(KEY, JSON.stringify(d));
const SETTINGS_COLUMNS = 'id,name_font_size,name_font_family,name_font_weight,name_color,name_align,name_x,name_y,name_rotation,name_letter_spacing,name_line_height,updated_at,updated_by';
function settingsFromRow(row) { if (!row) return null; return { fontSize: Number(row.name_font_size), fontFamily: row.name_font_family, bold: row.name_font_weight === '700' || row.name_font_weight === 'bold', color: row.name_color, align: row.name_align, x: Number(row.name_x), y: Number(row.name_y), rotation: Number(row.name_rotation || 0), letterSpacing: Number(row.name_letter_spacing || 0), lineHeight: Number(row.name_line_height || 1) }; }
async function loadGlobalSettings() { if (!db) return null; const { data, error } = await db.from('certificate_settings').select(SETTINGS_COLUMNS).eq('id', 'global').maybeSingle(); if (error) throw error; return settingsFromRow(data); }
async function saveGlobalSettings(s) { if (!db || !authenticatedUser) throw new Error('Authenticated Supabase admin session is required.'); const payload = { id:'global', name_font_size:Number(s.fontSize), name_font_family:s.fontFamily, name_font_weight:s.bold ? '700' : '400', name_color:s.color, name_align:s.align, name_x:Number(s.x), name_y:Number(s.y), name_rotation:Number(s.rotation || 0), name_letter_spacing:Number(s.letterSpacing || 0), name_line_height:Number(s.lineHeight || 1), updated_at:new Date().toISOString(), updated_by:authenticatedUser.id }; const { data, error } = await db.from('certificate_settings').upsert(payload, { onConflict:'id' }).select(SETTINGS_COLUMNS).single(); if (error) throw error; return settingsFromRow(data); }
const copy = t => navigator.clipboard?.writeText(t).then(() => alert('Copied to clipboard.')).catch(() => prompt('Copy this text:', t));
function debugSupabase(operation, error, extra = {}) {
  if (!error) { console.info(`[ACM Supabase] ${operation}: success`, extra); return; }
  const diagnosticTarget = operation.includes('student list') ? qs('#emptyState') : qs('#enrollResult');
  if (diagnosticTarget) {
    const diagnostic = { operation: operation.includes('student list') ? 'Student List' : 'Enrollment', httpStatus: error.status ?? error.statusCode ?? 'N/A', code: error.code ?? 'N/A', message: error.message ?? 'N/A', details: error.details ?? 'N/A', hint: error.hint ?? 'N/A', authenticatedUserId: authenticatedUser?.id ?? 'N/A', adminRoleDetected: authenticatedUser?.app_metadata?.role === 'admin' };
    diagnosticTarget.classList.remove('hidden');
    diagnosticTarget.style.whiteSpace = 'pre-wrap';
    diagnosticTarget.style.textAlign = 'left';
    diagnosticTarget.style.border = '1px solid #b33b3b';
    diagnosticTarget.style.background = '#fff4f3';
    diagnosticTarget.style.color = '#7d2525';
    diagnosticTarget.style.padding = '16px';
    diagnosticTarget.innerHTML = `<strong>Supabase diagnostic</strong>\n\nOperation: ${esc(diagnostic.operation)}\nHTTP Status: ${esc(diagnostic.httpStatus)}\nError Code: ${esc(diagnostic.code)}\nError Message: ${esc(diagnostic.message)}\nError Details: ${esc(diagnostic.details)}\nError Hint: ${esc(diagnostic.hint)}\nAuthenticated User ID: ${esc(diagnostic.authenticatedUserId)}\nAdmin Role Detected: ${esc(diagnostic.adminRoleDetected)}`;
  }
  console.error(`[ACM Supabase] ${operation}: error`, {
    operation,
    httpStatus: error.status ?? error.statusCode ?? null,
    code: error.code ?? null,
    message: error.message ?? null,
    details: error.details ?? null,
    hint: error.hint ?? null,
    ...extra
  });
}
function loadConfig() { return new Promise(resolve => { const finish = () => { const c = window.ACM_CONFIG || {}; if (window.supabase && c.SUPABASE_URL && !c.SUPABASE_URL.includes('YOUR-')) db = window.supabase.createClient(c.SUPABASE_URL, c.SUPABASE_ANON_KEY); resolve(); }; if (window.supabase) { const c = document.createElement('script'); c.src = 'js/config.js'; c.onload = finish; c.onerror = resolve; document.head.appendChild(c); } else { const s = document.createElement('script'); s.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2'; s.onload = () => { const c = document.createElement('script'); c.src = 'js/config.js'; c.onload = finish; c.onerror = resolve; document.head.appendChild(c); }; s.onerror = resolve; document.head.appendChild(s); } }); }
function makeCode() { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789', part = n => Array.from({ length:n }, () => chars[Math.floor(Math.random() * chars.length)]).join(''); return `ACM-${part(4)}-${part(4)}`; }
const LOCAL_TEMPLATE = 'assets/certificates/acm-certificate-template.png';
function showTemplateError(error) { const message = 'CERTIFICATE TEMPLATE ERROR\nUnable to load the official ACM certificate template.'; const target = qs('#certificateResult') || qs('.certificate-preview') || qs('#uploadStatus'); if (target) { let box = qs('#templateError'); if (!box) { box = document.createElement('pre'); box.id = 'templateError'; target.parentNode.insertBefore(box, target); } box.textContent = message; box.style.whiteSpace = 'pre-wrap'; box.style.padding = '14px'; box.style.border = '1px solid #b33b3b'; box.style.background = '#fff4f3'; box.style.color = '#7d2525'; } console.error('[ACM Template] load failed', error); }
function imageFor(d) { return new Promise((ok, no) => { const templateSrc = LOCAL_TEMPLATE; const resolvedSrc = new URL(templateSrc, document.baseURI).href; const img = new Image(); console.log('[ACM] document URL:', window.location.href); console.log('[ACM] template relative path:', templateSrc); console.log('[ACM] Template URL:', resolvedSrc); img.onload = () => { console.log('[ACM] Template complete:', img.complete); console.log('[ACM] Template currentSrc:', img.currentSrc); console.log('[ACM] Template naturalWidth:', img.naturalWidth); console.log('[ACM] Template naturalHeight:', img.naturalHeight); if (!img.complete || img.naturalWidth <= 0 || img.naturalHeight <= 0) { no(new Error('The official ACM certificate image has invalid natural dimensions.')); return; } ok(img); }; img.onerror = () => { console.error('[ACM] Template image failed to load', { src: img.src, currentSrc: img.currentSrc, complete: img.complete, naturalWidth: img.naturalWidth, naturalHeight: img.naturalHeight, documentURL: window.location.href, templateRelativePath: templateSrc, resolvedURL: resolvedSrc }); no(new Error(`Unable to load ${resolvedSrc}`)); }; img.src = templateSrc; }); }
async function draw(canvas, d, name = 'STUDENT FULL NAME') { try { const img = await imageFor(d); const scale = 1; canvas.width = img.naturalWidth; canvas.height = img.naturalHeight; const c = canvas.getContext('2d'); if (!c) throw new Error('Certificate canvas context is unavailable.'); const s = d.settings || DEFAULT.settings; c.clearRect(0, 0, canvas.width, canvas.height); c.drawImage(img, 0, 0, img.naturalWidth, img.naturalHeight); let size = s.fontSize * scale; c.font = `${s.bold ? '700 ' : ''}${size}px ${s.fontFamily}`; while (size > 18 * scale && c.measureText(name).width > canvas.width * .7) { size -= scale; c.font = `${s.bold ? '700 ' : ''}${size}px ${s.fontFamily}`; } c.fillStyle = s.color; c.textAlign = s.align; c.textBaseline = 'middle'; c.fillText(name, canvas.width * s.x, canvas.height * s.y); c.getImageData(0, 0, 1, 1); c.canvas.toDataURL('image/png'); return canvas; } catch (error) { showTemplateError(error); throw error; } }
const canonicalDraw = draw;
draw = async function renderCanonicalCertificate(canvas, d, name = 'STUDENT FULL NAME') { let renderData = d; if (qs('#verifyForm') && db) { try { const globalSettings = await loadGlobalSettings(); if (globalSettings) renderData = { ...d, settings: globalSettings }; else renderData = { ...d, settings: { ...DEFAULT.settings } }; } catch (error) { console.error('[ACM Settings] student load failed', error); renderData = { ...d, settings: { ...DEFAULT.settings } }; } } const rendered = await canonicalDraw(canvas, renderData, name); canvas.style.display = 'block'; canvas.style.width = '100%'; canvas.style.maxWidth = '100%'; canvas.style.height = 'auto'; canvas.style.transform = 'none'; const frame = canvas.parentElement; if (frame) { frame.style.width = '100%'; frame.style.maxWidth = '100%'; frame.style.minWidth = '0'; frame.style.overflowX = 'hidden'; frame.style.boxSizing = 'border-box'; } return rendered; };
function showDownloadError(type, error) { const box = qs('#downloadError') || (() => { const el = document.createElement('pre'); el.id = 'downloadError'; el.style.whiteSpace = 'pre-wrap'; el.style.marginTop = '16px'; el.style.padding = '14px'; el.style.border = '1px solid #b33b3b'; el.style.background = '#fff4f3'; el.style.color = '#7d2525'; qs('.download-actions')?.after(el); return el; })(); const message = error?.message || String(error || 'Unknown error'); box.textContent = `${type} DOWNLOAD ERROR\nError:\n${message}`; console.error(`[ACM Download] ${type} failed`, error); }
function assertCanvas(canvas) { if (!canvas || !(canvas instanceof HTMLCanvasElement)) throw new Error('Certificate canvas is missing.'); if (!canvas.width || !canvas.height) throw new Error('Certificate canvas has invalid dimensions.'); const context = canvas.getContext('2d'); if (!context) throw new Error('Certificate canvas context is unavailable.'); try { context.getImageData(0, 0, 1, 1); const png = canvas.toDataURL('image/png'); if (!png.startsWith('data:image/png')) throw new Error('PNG canvas export returned an invalid data URL.'); } catch (error) { throw new Error(`Certificate canvas is not exportable: ${error.message}`); } return context; }
function downloadPng(canvas, name) { assertCanvas(canvas); return new Promise((resolve, reject) => { canvas.toBlob(blob => { try { if (!blob || blob.type !== 'image/png' || !blob.size) throw new Error('PNG blob generation returned an invalid blob.'); const a = document.createElement('a'); a.download = `ACM-Certificate-${name.replace(/\s+/g, '-')}.png`; a.href = URL.createObjectURL(blob); a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); resolve(); } catch (error) { reject(error); } }, 'image/png'); }); }
function downloadPdf(canvas, name) { assertCanvas(canvas); const w = canvas.width, h = canvas.height, dataUrl = canvas.toDataURL('image/jpeg', .94), raw = atob(dataUrl.split(',')[1]), jpg = Uint8Array.from(raw, c => c.charCodeAt(0)); const content = `q ${w} 0 0 ${h} 0 0 cm /Im Do Q\n`, objects = [`1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n`, `2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n`, `3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /XObject << /Im 5 0 R >> >> /Contents 4 0 R >>endobj\n`, `4 0 obj<< /Length ${new TextEncoder().encode(content).length} >>stream\n${content}endstream\nendobj\n`, `5 0 obj<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>stream\n`]; let chunks = [new TextEncoder().encode('%PDF-1.3\n')], offsets = [0]; objects.forEach(o => { offsets.push(chunks.reduce((n, b) => n + b.length, 0)); chunks.push(new TextEncoder().encode(o)); }); chunks.push(jpg, new TextEncoder().encode('\nendstream\nendobj\n')); const xref = chunks.reduce((n, b) => n + b.length, 0); chunks.push(new TextEncoder().encode(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(v => String(v).padStart(10, '0') + ' 00000 n \n').join('')}trailer<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`)); const blob = new Blob(chunks, { type:'application/pdf' }); if (!blob.size) throw new Error('PDF blob generation returned an empty blob.'); const a = document.createElement('a'); a.download = `ACM-Certificate-${name.replace(/\s+/g, '-')}.pdf`; a.href = URL.createObjectURL(blob); a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
function whatsapp(s) { const link = location.href.replace('admin.html', 'certificate.html') + '?code=' + s.certificate_code; open(`https://wa.me/?text=${encodeURIComponent(`Hello ${s.student_name},\n\nYour Arewa Connect Movement certificate is ready.\n\nCertificate Code: ${s.certificate_code}\n\nDownload your certificate here:\n${link}\n\nThank you.`)}`, '_blank'); }
async function initAdmin() {
  if (!qs('#loginView')) return;
  const form = qs('#loginForm'), label = document.createElement('label'); label.innerHTML = 'Admin email<input id="adminEmail" type="email" placeholder="admin@example.com" autocomplete="username" required>'; form.insertBefore(label, form.firstElementChild);
  const session = db && (await db.auth.getSession()).data.session;
  authenticatedUser = session?.user ?? null;
  console.info('[ACM Auth] session check', { userId: session?.user?.id ?? null, appMetadataRole: session?.user?.app_metadata?.role ?? null, roleDetected: session?.user?.app_metadata?.role === 'admin' });
  if (session?.user?.app_metadata?.role === 'admin') await showDashboard(session.user);
  form.onsubmit = async e => { e.preventDefault(); if (!db) { qs('#loginError').textContent = 'Supabase is not configured.'; return; } const { data, error } = await db.auth.signInWithPassword({ email: qs('#adminEmail').value.trim(), password: qs('#adminPassword').value }); authenticatedUser = data?.user ?? null; debugSupabase('auth.signInWithPassword', error, { userId: data?.user?.id ?? null, appMetadataRole: data?.user?.app_metadata?.role ?? null, roleDetected: data?.user?.app_metadata?.role === 'admin' }); if (error || data.user?.app_metadata?.role !== 'admin') { await db.auth.signOut(); qs('#loginError').textContent = error ? 'Unable to sign in. Check your email and password.' : 'This account is not authorized as an ACM administrator.'; return; } await showDashboard(data.user); };
  db?.auth.onAuthStateChange((event, s) => { if (event === 'SIGNED_OUT' || (s && s.user.app_metadata?.role !== 'admin' && qs('#dashboard') && !qs('#dashboard').classList.contains('hidden'))) location.reload(); });
  async function showDashboard(user) {
    qs('#loginView').classList.add('hidden'); qs('#dashboard').classList.remove('hidden');
    const head = qs('.page-heading'); const status = document.createElement('span'); status.className = 'status-pill'; status.textContent = 'Authenticated as Admin'; head.firstElementChild.appendChild(status);
    let d = settings(), canvas = qs('#templateCanvas'); try { const globalSettings = await loadGlobalSettings(); if (globalSettings) d.settings = globalSettings; else d.settings = { ...DEFAULT.settings }; } catch (error) { d.settings = { ...DEFAULT.settings }; qs('#templateSaved').textContent = 'Unable to load global certificate settings.'; console.error('[ACM Settings] load failed', error); } ['fontSize','fontFamily','fontBold','fontColor','textAlign'].forEach(id => { const key = {fontSize:'fontSize',fontFamily:'fontFamily',fontBold:'bold',fontColor:'color',textAlign:'align'}[id]; qs('#'+id).value = d.settings[key]; }); qs('#fontBold').checked = d.settings.bold; await draw(canvas, d); await renderRows();
    qs('#logoutBtn').onclick = async () => { await db.auth.signOut(); location.reload(); };
    qs('#templateUpload').onchange = e => { const f = e.target.files[0], r = new FileReader(); r.onload = async () => { d.template = r.result; saveSettings(d); await draw(canvas, d); qs('#uploadStatus').textContent = 'Template uploaded and ready.'; }; if (f) r.readAsDataURL(f); };
    ['fontSize','fontFamily','fontBold','fontColor','textAlign'].forEach(id => qs('#'+id).oninput = async () => { d.settings = { ...d.settings, fontSize:+qs('#fontSize').value, fontFamily:qs('#fontFamily').value, bold:qs('#fontBold').checked, color:qs('#fontColor').value, align:qs('#textAlign').value }; await draw(canvas, d); });
    canvas.onpointerdown = e => { const move = ev => { const r = canvas.getBoundingClientRect(); d.settings.x = Math.max(0, Math.min(1, (ev.clientX-r.left)/r.width)); d.settings.y = Math.max(0, Math.min(1, (ev.clientY-r.top)/r.height)); draw(canvas, d); }; const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); }; addEventListener('pointermove', move); addEventListener('pointerup', up); };
    qs('#saveTemplate').onclick = async () => { try { d.settings = { ...d.settings, fontSize:+qs('#fontSize').value, fontFamily:qs('#fontFamily').value, bold:qs('#fontBold').checked, color:qs('#fontColor').value, align:qs('#textAlign').value }; if (!Number.isFinite(d.settings.fontSize) || d.settings.fontSize < 12 || d.settings.fontSize > 300) throw new Error('Font size must be between 12 and 300.'); const saved = await saveGlobalSettings(d.settings); d.settings = saved; saveSettings(d); await draw(canvas, d); qs('#templateSaved').textContent = 'Template position saved globally.'; } catch (error) { qs('#templateSaved').textContent = 'Unable to save global certificate settings.'; console.error('[ACM Settings] save failed', error); } };
    qs('#enrollForm').onsubmit = async e => { e.preventDefault(); const row = { student_name:qs('#studentName').value.trim(), certificate_code:makeCode(), status:'ACTIVE' }; const { data, error } = await db.from('acm_certificates').insert(row).select('student_name,certificate_code,status,created_at').single(); debugSupabase('acm_certificates INSERT + SELECT', error, { table: 'acm_certificates', columns: Object.keys(row), authenticatedUserId: authenticatedUser?.id ?? null, expectedAdminRole: 'admin' }); const result = qs('#enrollResult'); result.classList.remove('hidden'); if (error) { result.innerHTML = '<b>Unable to enroll student.</b>'; return; } result.innerHTML = `<b>Student enrolled</b><div>Student Name: ${esc(data.student_name)}</div><div>Certificate Code: <code>${data.certificate_code}</code></div><div class="actions"><button class="button button-outline copy-code">Copy Code</button><button class="button button-outline copy-link">Copy Link</button><button class="button button-gold send-wa">Send via WhatsApp</button></div>`; qs('.copy-code').onclick = () => copy(data.certificate_code); qs('.copy-link').onclick = () => copy(location.href.replace('admin.html','certificate.html')+'?code='+data.certificate_code); qs('.send-wa').onclick = () => whatsapp(data); qs('#studentName').value = ''; renderRows(); };
  }
  async function renderRows() { const { data, error } = await db.from('acm_certificates').select('id,student_name,certificate_code,status,created_at').order('created_at', {ascending:false}); debugSupabase('acm_certificates SELECT student list', error, { table: 'acm_certificates', selectedColumns: ['id','student_name','certificate_code','status','created_at'], authenticatedUserId: authenticatedUser?.id ?? null, expectedAdminRole: 'admin' }); const rows = qs('#studentRows'); rows.innerHTML = ''; if (error) { qs('#emptyState').textContent = 'Unable to load certificates.'; return; } qs('#studentCount').textContent = (data || []).length + ' total'; qs('#emptyState').classList.toggle('hidden', !!data?.length); (data || []).forEach(s => { const tr = document.createElement('tr'); tr.innerHTML = `<td><b>${esc(s.student_name)}</b></td><td><code>${s.certificate_code}</code></td><td>${new Date(s.created_at).toLocaleDateString()}</td><td class="status-${s.status.toLowerCase()}">${s.status}</td><td><div class="actions"><button class="button button-outline copy-row">Copy</button><button class="button button-outline wa-row">WhatsApp</button><button class="button button-outline revoke-row">${s.status==='ACTIVE'?'Revoke':'Restore'}</button></div></td>`; tr.querySelector('.copy-row').onclick = () => copy(s.certificate_code); tr.querySelector('.wa-row').onclick = () => whatsapp(s); tr.querySelector('.revoke-row').onclick = async () => { await db.from('acm_certificates').update({status:s.status==='ACTIVE'?'REVOKED':'ACTIVE'}).eq('id',s.id); renderRows(); }; rows.appendChild(tr); }); }
}
async function initStudent() { if (!qs('#verifyForm')) return; const d = settings(), param = new URLSearchParams(location.search).get('code'); if (param) qs('#certificateCode').value = param; qs('#verifyForm').onsubmit = async e => { e.preventDefault(); const msg = qs('#verifyMessage'); if (!db) { msg.className='message error'; msg.textContent='Certificate portal is not configured yet.'; return; } const { data, error } = await db.rpc('get_acm_certificate', {p_code:qs('#certificateCode').value.trim()}); const s = data?.[0]; if (error || !s) { msg.className='message error'; msg.textContent='Certificate code not found. Please check your code and try again.'; qs('#certificateResult').classList.add('hidden'); return; } if (s.status === 'REVOKED') { msg.className='message error'; msg.textContent='Certificate unavailable.'; qs('#certificateResult').classList.add('hidden'); return; } msg.className='message success'; msg.textContent='Certificate verified successfully.'; qs('#certificateResult').classList.remove('hidden'); qs('#holderName').textContent=s.student_name; const canvas=qs('#certificateCanvas'); await draw(canvas,d,s.student_name); const track=()=>db.rpc('record_acm_download',{p_code:qs('#certificateCode').value.trim()}); qs('#downloadPng').onclick=()=>{downloadPng(canvas,s.student_name);track()}; qs('#downloadPdf').onclick=()=>{downloadPdf(canvas,s.student_name);track()}; } }
function installSearch() { const panel = qs('.student-panel .panel-heading'); if (!panel || qs('#studentSearch')) return false; const input = document.createElement('input'); input.id = 'studentSearch'; input.type = 'search'; input.placeholder = 'Search students or codes'; input.style.maxWidth = '220px'; panel.insertBefore(input, panel.lastElementChild); input.oninput = () => { const q = input.value.toLowerCase(); qs('#studentRows').querySelectorAll('tr').forEach(row => row.style.display = row.textContent.toLowerCase().includes(q) ? '' : 'none'); }; return true; }
const rawDownloadPng = downloadPng;
downloadPng = async (canvas, name) => { try { return await rawDownloadPng(canvas, name); } catch (error) { showDownloadError('PNG', error); return false; } };
const rawDownloadPdf = downloadPdf;
downloadPdf = (canvas, name) => { try { return rawDownloadPdf(canvas, name); } catch (error) { showDownloadError('PDF', error); return false; } };
loadConfig().then(() => { initAdmin(); initStudent(); const timer = setInterval(() => { if (installSearch()) clearInterval(timer); }, 250); });
